### ISSUE TITLE
App crashes when using camera to add a picture

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-ios#238] opened 2015-11-09 15:35 UTC
Reported bug: app crashes when adding a photo using the camera (6s+) but does not crash when adding a photo from an existing album. Currently not replicated (so far tested on a 6+).

**Comment by jmorrison1847** [comment] 2015-11-09 15:36
Could be related to #78

**Comment by jwalgran** [comment] 2016-02-09 15:19
Clearing the date-based milestone because we have switched to release number milestones

**Comment by jwalgran** [comment] 2017-08-24 16:44
Closing as duplicate of #78

**Closed by jwalgran** 2017-08-24 16:44 UTC
Labels: bug
