### ISSUE TITLE
If a user is not allowed to add trees we let them try and get an error

### ISSUE THREAD

**Issue by RickMohr** [OpenTreeMap/otm-ios#282] opened 2016-03-04 18:52 UTC
We should hide or disable the "Add" button, rather than letting them do everything and then get an error trying to save the tree.

**Comment by jwalgran** [comment] 2016-04-12 15:40
Duplicate of https://github.com/OpenTreeMap/otm-ios/issues/109

**Closed by jwalgran** 2016-04-12 15:40 UTC
Labels: bug
