### ISSUE TITLE
Plotted points on iOS appear in different locations when viewed with the web app

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-ios#233] opened 2015-09-11 18:42 UTC
The Greening of Detroit reported this anomaly—I've replicated in on Philly Tree Map below.

The four plotted points (one on each corner of the intersection) as they appear on the iOS app: 
![img_4636](https://cloud.githubusercontent.com/assets/12401491/9822999/a7984496-5891-11e5-99c9-6b343a64cc22.PNG)
And as they appear on the web app, subsequently:
![screen shot 2015-09-11 at 2 16 06 pm](https://cloud.githubusercontent.com/assets/12401491/9823277/487fe2fa-5893-11e5-8689-43d6b00f2ca9.png)

**Comment by jwalgran** [comment] 2015-09-11 22:49
Another data point. The Android app looks like web app.

![screenshot_2015-09-11-15-40-24](https://cloud.githubusercontent.com/assets/17363/9827864/a08b5e54-589b-11e5-8604-868d35118817.png)


![image1-3](https://cloud.githubusercontent.com/assets/17363/9827933/527bef20-589c-11e5-8240-fca6c121f5d5.PNG)

**Comment by dboyer** [comment] 2015-09-16 16:28
LA users have seen a similar issue. May be related to Apple maps.

**Comment by jmorrison1847** [comment] 2015-12-01 21:05
Also noted by a recent user.

**Comment by jmorrison1847** [comment] 2015-12-01 21:09
Recently noted by Dale Carlon as a top priority

**Comment by handerton** [comment] 2015-12-03 18:00
Dale Carlon is having a similar but slightly different issue.  When we plot a point in the iOS app and click add, it is immediately off-target... not just in the web app.  Looks like this is a known issue since at least September -- please update on progress.

**Comment by jwalgran** [comment] 2015-12-15 17:36
There is a precision problem in the iOS app that is addressed in #248. It fixes the most glaring issue, but there are some other problems with having two different map providers that cannot be fully eliminated.

Google and Apple use different street layers. Adding a planting site by "eyeballing" it relative to the rendered street map will not be accurate. This screenshot shows the same intersection. The planting sites are in roughly the same relative location on both apps, but the street widths and building footprints are very different.

<img width="826" alt="screen shot 2015-12-15 at 10 03 09 am" src="https://cloud.githubusercontent.com/assets/17363/11817736/9230ebfe-a313-11e5-8ea6-3f6981535d95.png">

Though Google and Apple use different satellite imagery, points added relative to features in the imagery will be more accurate. This screenshot show a planting site added from the iOS app at the corner of painted lines in a parking lot appearing in the same location on the Google satellite layer.

<img width="967" alt="screen shot 2015-12-15 at 8 51 53 am" src="https://cloud.githubusercontent.com/assets/17363/11817506/60595fc2-a312-11e5-893f-787f96a5c403.png">

There may be some confusion being caused by the fact that we are currently allow zooming up to level 21 on the website. This screencast shows how precision problems at this scale are exaggerated.
  
![google-zoom-20-21](https://cloud.githubusercontent.com/assets/17363/11818011/19c03ea2-a315-11e5-846f-e260461e382e.gif)

**Comment by jmorrison1847** [comment] 2015-12-15 18:22
@jwalgran Thank you for the thorough explanation, this is incredibly helpful.

**Comment by maurizi** [comment] 2015-12-15 18:25
We might be able to alleviate some of this confusion by switching to the hybrid layer instead of the streets layer when adding a tree in all 3 applications (Web, iOS and Android), since the satellite view is more consistent across basemaps and zoom levels.

**Comment by jmorrison1847** [comment] 2015-12-16 14:16
+1 to @maurizi—I am constantly advising people to use hybrid or satellite mode when adding trees, and it makes perfect sense to me to make that an assumption built into the software. The less manual steps that need to be taken, the better.

**Closed** 2015-12-17 19:40 UTC
Labels: unverified
