### ISSUE TITLE
Delete Trees on Mobile

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-ios#335] opened 2016-11-22 18:54 UTC
Related to https://github.com/OpenTreeMap/otm-android/issues/289, Baton Rouge Green (and Leaf & Limb Consulting) have requested the ability to delete trees on the mobile apps.

**Comment by jwalgran** [comment] 2017-08-24 22:06
Duplicate of #249

**Closed** 2017-08-24 22:07 UTC
Labels: bug, high
