### ISSUE TITLE
"Add another trunk" option on mobile

### ISSUE THREAD

**Issue by jmorrison1847** [OpenTreeMap/otm-ios#286] opened 2016-03-14 20:52 UTC
TreeFolks has requested the ability to add the functionality of the additional trunk calculations to the mobile workflow.

Related to https://github.com/OpenTreeMap/otm-android/issues/256

**Comment by jwalgran** [comment] 2017-08-24 19:03
Duplicate of #145

**Closed by jwalgran** 2017-08-24 19:03 UTC
Labels: enhancement
